### ISSUE TITLE
about page framing/layout

### ISSUE THREAD

**Issue by jjallaire** [walkerke/neighborhood_diversity#1]
I noticed that the content on the about page is unframed. I just made a change to flexdashboard to automatically place a frame (+ scroll container) around the content of pages that have no dashboard components in them. Net: if you update to the latest flexdashboard from GitHub your about page will look much nicer.

**Comment by walkerke** [comment]
That's great, thank you!  I'll update flexdashboard and republish soon.

**Comment by walkerke** [comment]
Just tested locally, it looks great.  The flexdashboard package is fantastic, I've really enjoyed working with it.

**Comment by walkerke** [comment]
Published the updates.

**Comment by jjallaire** [comment]
Thanks! I'm just about to post a link to flexdashboard on twitter. Your
dashboard looks so good I think I'll include a picture of it in the tweet!
:-)

**Comment by walkerke** [comment]
Saw the tweet - I really appreciate it!
